package cwk;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;

/**
 *
 * @author UP683693
 */
public class MainFrame extends javax.swing.JFrame {

    Order order = new Order();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        boxList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        dimensionPanel = new javax.swing.JPanel();
        boxWidthTB = new javax.swing.JTextField();
        boxDepthTB = new javax.swing.JTextField();
        boxHeightTB = new javax.swing.JTextField();
        cardGradeCoB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numColorsCoB = new javax.swing.JComboBox();
        reinforcedBottomChB = new javax.swing.JCheckBox();
        reinforcedCornersChB = new javax.swing.JCheckBox();
        sealableTopChB = new javax.swing.JCheckBox();
        resetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addToOrderBTN = new javax.swing.JButton();
        qtySpn = new javax.swing.JSpinner();
        costLbl = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlexBox");

        boxList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(boxList);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Box Properties"));

        dimensionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensions"));

        boxWidthTB.setText("Width");

        boxDepthTB.setText("Depth");

        boxHeightTB.setText("Height");

        javax.swing.GroupLayout dimensionPanelLayout = new javax.swing.GroupLayout(dimensionPanel);
        dimensionPanel.setLayout(dimensionPanelLayout);
        dimensionPanelLayout.setHorizontalGroup(
            dimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxWidthTB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxDepthTB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxHeightTB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dimensionPanelLayout.setVerticalGroup(
            dimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxWidthTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDepthTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxHeightTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DimensionVarifier dv = new DimensionVarifier(message);
        boxWidthTB.setInputVerifier(dv);
        boxDepthTB.setInputVerifier(dv);
        boxHeightTB.setInputVerifier(dv);

        cardGradeCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        cardGradeCoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardGradeCoBFocusLost(evt);
            }
        });

        jLabel2.setLabelFor(cardGradeCoB);
        jLabel2.setText("Card Grade");

        jLabel3.setText("Colours");

        numColorsCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No colours", "1 Colour", "2 Colours" }));
        numColorsCoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numColorsCoBFocusLost(evt);
            }
        });

        reinforcedBottomChB.setText("Reinforced Bottom");
        reinforcedBottomChB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reinforcedBottomChBFocusLost(evt);
            }
        });

        reinforcedCornersChB.setText("Reinforced Corners");
        reinforcedCornersChB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reinforcedCornersChBFocusLost(evt);
            }
        });

        sealableTopChB.setText("Sealable Top");

        resetBtn.setText("Reset");
        resetBtn.setToolTipText("Clears box properties. Doesn't cancel the order.");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numColorsCoB, 0, 103, Short.MAX_VALUE)
                            .addComponent(cardGradeCoB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(dimensionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(sealableTopChB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(reinforcedBottomChB)
                            .addGap(18, 18, 18)
                            .addComponent(reinforcedCornersChB))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dimensionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cardGradeCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numColorsCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reinforcedBottomChB)
                    .addComponent(reinforcedCornersChB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sealableTopChB)
                    .addComponent(resetBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total Cost: ");
        jLabel1.setFocusable(false);

        jLabel4.setText("Quantity");

        addToOrderBTN.setText("Add to Order");
        addToOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToOrderBTNActionPerformed(evt);
            }
        });

        qtySpn.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costLbl))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(qtySpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addToOrderBTN))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(qtySpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addToOrderBTN))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(costLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message)
                    .addComponent(quitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToOrderBTNActionPerformed
        BoxMaker boxMaker;
        try {
            boxMaker = new BoxMaker(Double.parseDouble(boxWidthTB.getText()),
                    Double.parseDouble(boxWidthTB.getText()),
                    Double.parseDouble(boxHeightTB.getText()),
                    reinforcedBottomChB.getSelectedObjects() != null,
                    reinforcedCornersChB.getSelectedObjects() != null,
                    sealableTopChB.getSelectedObjects() != null,
                    cardGradeCoB.getSelectedItem(), numColorsCoB.getSelectedItem(),
                    (int) qtySpn.getValue());
            order.add(boxMaker.createBox());
        }
        catch (NumberFormatException nfe) {
            validateInputs();
            return;
        }
        boxList.setListData(order.getBoxes());
        message.setText(boxMaker.getMessage());
        costLbl.setText(order.getTotalCostStr());
        
    }//GEN-LAST:event_addToOrderBTNActionPerformed

    private void validateInputs() {
        DimensionVarifier dv = (DimensionVarifier) boxWidthTB.getInputVerifier();

        // User should be contained in text box if they submit invalid data
        // This method protects against user not going into the textboxes
        // Reverse order so will move to leftmost error first. 
        if (!dv.verify(boxWidthTB))
            boxWidthTB.requestFocusInWindow();
        if (!dv.verify(boxDepthTB))
            boxDepthTB.requestFocusInWindow();
        if (!dv.verify(boxHeightTB))
            boxHeightTB.requestFocusInWindow();
    }

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        boxWidthTB.setText("Width");
        boxDepthTB.setText("Depth");
        boxHeightTB.setText("Height");

        cardGradeCoB.setSelectedIndex(0);
        cardGradeCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5"}));
        numColorsCoB.setSelectedIndex(0);
        numColorsCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"No colours", "1 Colour", "2 Colours"}));

        reinforcedBottomChB.setSelected(false);
        reinforcedBottomChB.setEnabled(true);
        reinforcedCornersChB.setSelected(false);
        reinforcedCornersChB.setEnabled(true);
        sealableTopChB.setSelected(false);

        qtySpn.setValue(0);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void cardGradeCoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardGradeCoBFocusLost
        JComboBox cb = (JComboBox) evt.getSource();

        switch (cb.getSelectedItem().toString()) {
            case "Grade 1":
                // 0 CP
                filterLists(numColorsCoB, false, new Object[]{"1 Colour", "2 Colours"});
                // !RB
                setLockChB(reinforcedBottomChB, false);
                // !RC
                setLockChB(reinforcedCornersChB, false);
                return;

            case "Grade 2":
                // !RC
                setLockChB(reinforcedCornersChB, false);
                return;

            case "Grade 4":
                // 1 .. 2 CP
                filterLists(numColorsCoB, false, new Object[]{"No colours"});
                return;

            case "Grade 5":
                // 2 CP
                filterLists(numColorsCoB, false, new Object[]{"No colours", "1 Colour"});
                return;
        }
    }//GEN-LAST:event_cardGradeCoBFocusLost

    private void numColorsCoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numColorsCoBFocusLost
        JComboBox cb = (JComboBox) evt.getSource();

        switch (cb.getSelectedItem().toString()) {
            case "No colours":
                // 1 ..3 Cg
                filterLists(cardGradeCoB, true, new Object[]{"Grade 4", "Grade 5"});
                // !RB
                setLockChB(reinforcedBottomChB, false);
                // !RC
                setLockChB(reinforcedCornersChB, false);
                return;

            case "1 Colour":
                // 2 .. 4 Cg
                filterLists(cardGradeCoB, true, new Object[]{"Grade 1", "Grade 5"});
                // !RB
                setLockChB(reinforcedBottomChB, false);
                // !RC
                setLockChB(reinforcedCornersChB, false);
                return;

            case "2 Colours":
                // 2 .. 5 Cg
                filterLists(cardGradeCoB, true, new Object[]{"Grade 1"});
                return;
        }
    }//GEN-LAST:event_numColorsCoBFocusLost

    private void reinforcedBottomChBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reinforcedBottomChBFocusLost
        JCheckBox chB = (JCheckBox) evt.getSource();
        if (chB.getSelectedObjects() != null){ 
            // No action when not checked. Don't want issues for people tabing past
            // 2 .. 5 cg
            filterLists(cardGradeCoB, true, new Object[]{"Grade 1"});
            // 2 cp
            filterLists(numColorsCoB, false, new Object[]{"No colours", "1 Colour"});
        }
    }//GEN-LAST:event_reinforcedBottomChBFocusLost

    private void reinforcedCornersChBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reinforcedCornersChBFocusLost
        JCheckBox chB = (JCheckBox) evt.getSource();
        if (chB.getSelectedObjects() != null){
            // 3 .. 5 cg
            filterLists(cardGradeCoB, true, new Object[]{"Grade 1", "Grade 2"});
            //  2 cp
            filterLists(numColorsCoB, false, new Object[]{"No colours", "1 Colour"});
            // RB
            setLockChB(reinforcedBottomChB, true);
        }
    }//GEN-LAST:event_reinforcedCornersChBFocusLost

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed

    //<editor-fold defaultstate="collapsed" desc="gui element mutators">
    private void setLockChB(JCheckBox chB, boolean state) {
        chB.setEnabled(false);
        chB.setSelected(state);
    }

    private void filterLists(JComboBox coB, boolean isCardGrade, Object[] invalidOptions) {
        ArrayList<String> allOptions = new ArrayList(); // Store all values for gui element
        Object selected = coB.getSelectedItem();
        if (isCardGrade) {
            String[] cardOptions = {"Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5"};
            allOptions.addAll(Arrays.asList(cardOptions));
        } else {
            String[] colourOptions = {"No colours", "1 Colour", "2 Colours"};
            allOptions.addAll(Arrays.asList(colourOptions));
        }

        for (Object ob : invalidOptions)
            allOptions.remove((String) ob);
        coB.setModel(new DefaultComboBoxModel(allOptions.toArray()));
        if (allOptions.contains(selected)){
            coB.setSelectedItem(selected);
        }
    }
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToOrderBTN;
    private javax.swing.JTextField boxDepthTB;
    private javax.swing.JTextField boxHeightTB;
    private javax.swing.JList boxList;
    private javax.swing.JTextField boxWidthTB;
    private javax.swing.JComboBox cardGradeCoB;
    private javax.swing.JLabel costLbl;
    private javax.swing.JPanel dimensionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JComboBox numColorsCoB;
    private javax.swing.JSpinner qtySpn;
    private javax.swing.JButton quitBtn;
    private javax.swing.JCheckBox reinforcedBottomChB;
    private javax.swing.JCheckBox reinforcedCornersChB;
    private javax.swing.JButton resetBtn;
    private javax.swing.JCheckBox sealableTopChB;
    // End of variables declaration//GEN-END:variables
}
