/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwk;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;

/**
 *
 * @author Andrew
 */
public class MainFrame extends javax.swing.JFrame {

    Order order = new Order();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        boxList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dimensionPanel = new javax.swing.JPanel();
        boxWidthTB = new javax.swing.JTextField();
        boxDepthTB = new javax.swing.JTextField();
        boxHeightTB = new javax.swing.JTextField();
        areaLabel = new javax.swing.JLabel();
        cardGradeCoB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numColorsCoB = new javax.swing.JComboBox();
        reinforcedBottomChB = new javax.swing.JCheckBox();
        reinforcedCornersChB = new javax.swing.JCheckBox();
        sealableTopChB = new javax.swing.JCheckBox();
        resetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addToOrderBTN = new javax.swing.JButton();
        qtySpn = new javax.swing.JSpinner();
        costLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlexBox");

        boxList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        boxList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                boxListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(boxList);

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Box Properties"));

        dimensionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensions"));

        boxWidthTB.setText("Width");

        boxDepthTB.setText("Depth");

        boxHeightTB.setText("Height");

        areaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        areaLabel.setLabelFor(dimensionPanel);
        areaLabel.setText("Total Area: ");

        javax.swing.GroupLayout dimensionPanelLayout = new javax.swing.GroupLayout(dimensionPanel);
        dimensionPanel.setLayout(dimensionPanelLayout);
        dimensionPanelLayout.setHorizontalGroup(
            dimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxWidthTB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxDepthTB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxHeightTB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(areaLabel)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        dimensionPanelLayout.setVerticalGroup(
            dimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dimensionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxWidthTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDepthTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxHeightTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DimensionVarifier dv = new DimensionVarifier();
        boxWidthTB.setInputVerifier(dv);
        boxDepthTB.setInputVerifier(dv);
        boxHeightTB.setInputVerifier(dv);

        cardGradeCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Card Grade", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        cardGradeCoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardGradeCoBFocusLost(evt);
            }
        });

        jLabel2.setLabelFor(cardGradeCoB);
        jLabel2.setText("Card Grade");

        jLabel3.setText("Colours");

        numColorsCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No colours", "1 Colour", "2 Colours" }));
        numColorsCoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numColorsCoBFocusLost(evt);
            }
        });

        reinforcedBottomChB.setText("Reinforced Bottom");

        reinforcedCornersChB.setText("Reinforced Corners");

        sealableTopChB.setText("Sealable Top");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dimensionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numColorsCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardGradeCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reinforcedBottomChB)
                                .addGap(18, 18, 18)
                                .addComponent(reinforcedCornersChB)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sealableTopChB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dimensionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cardGradeCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numColorsCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reinforcedBottomChB)
                    .addComponent(reinforcedCornersChB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sealableTopChB)
                    .addComponent(resetBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total Cost: ");
        jLabel1.setFocusable(false);

        jLabel4.setText("Quantity");

        addToOrderBTN.setText("Add to Order");
        addToOrderBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToOrderBTNActionPerformed(evt);
            }
        });

        qtySpn.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        costLbl.setText("cost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costLbl))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(qtySpn))
                            .addComponent(addToOrderBTN))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(qtySpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(costLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(addToOrderBTN))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] list = {"War", "Famine", "Plague", "Death", "Rhonnie"};
        boxList.setListData(list);
        System.out.println(boxList.getModel().toString());
        System.out.println(boxList.getModel().getClass());
        
        filterLists(cardGradeCoB, null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addToOrderBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToOrderBTNActionPerformed
        try {
            BoxMaker bm = new BoxMaker(Double.parseDouble(boxWidthTB.getText()),
                    Double.parseDouble(boxWidthTB.getText()),
                    Double.parseDouble(boxHeightTB.getText()),
                    reinforcedBottomChB.getSelectedObjects() != null,
                    reinforcedCornersChB.getSelectedObjects() != null,
                    sealableTopChB.getSelectedObjects() != null,
                    cardGradeCoB.getSelectedIndex(), numColorsCoB.getSelectedIndex(),
                    (int) qtySpn.getValue());
            order.add(bm.createBox());
            boxList.setListData(order.getBoxes());
            costLbl.setText(order.getTotalCostStr());
        } catch (NumberFormatException nfe) {
//            System.err.println(nfe);
            validateInputs();
        }
    }//GEN-LAST:event_addToOrderBTNActionPerformed

    private void validateInputs() {
        DimensionVarifier dv = (DimensionVarifier) boxWidthTB.getInputVerifier();

        // Reverse order so will move to leftmost error first. 
        if (!dv.verify(boxWidthTB))
            boxWidthTB.requestFocusInWindow();
        if (!dv.verify(boxDepthTB))
            boxDepthTB.requestFocusInWindow();
        if (!dv.verify(boxHeightTB))
            boxHeightTB.requestFocusInWindow();

    }

    private void boxListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_boxListValueChanged
        System.out.println("pass");
    }//GEN-LAST:event_boxListValueChanged

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        boxWidthTB.setText("Width");
        boxDepthTB.setText("Depth");
        boxHeightTB.setText("Height");

        cardGradeCoB.setSelectedIndex(0);
        numColorsCoB.setSelectedIndex(0);

        reinforcedBottomChB.setSelected(false);
        reinforcedCornersChB.setSelected(false);
        sealableTopChB.setSelected(false);

        qtySpn.setValue(0);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void cardGradeCoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardGradeCoBFocusLost
        JComboBox cb = (JComboBox) evt.getSource();

        switch (cb.getSelectedItem().toString()) {
            case "Card Grade":
            // Pass
            return;
            case "Grade 1":
            // 0 CP
            // !RB
            setLockChB(reinforcedBottomChB, false);
            // !RC
            setLockChB(reinforcedCornersChB, false);
            return;

            case "Grade 2":
            // 0 .. 2 CP
            // !RC
            setLockChB(reinforcedCornersChB, false);
            return;

            case "Grade 3":
            // 0 .. 2 CP
            return;

            case "Grade 4":
            // 1 .. 2 CP
            return;

            case "Grade 5":
            // 2 CP
            return;
        }
    }//GEN-LAST:event_cardGradeCoBFocusLost

    private void numColorsCoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numColorsCoBFocusLost
        JComboBox cb = (JComboBox) evt.getSource();

        switch (cb.getSelectedItem().toString()) {
            case "No colour":
            // 1 ..3 Cg
            // !RB
            setLockChB(reinforcedBottomChB, false);
            // !RC
            setLockChB(reinforcedCornersChB, false);
            return;

            case "1 Colour":
            // 2 .. 4 Cg
            // !RB
            setLockChB(reinforcedBottomChB, false);
            // !RC
            setLockChB(reinforcedCornersChB, false);
            return;

            case "2 Colours":
            // 2 .. 5 Cg
            return;
        }
    }//GEN-LAST:event_numColorsCoBFocusLost

    //<editor-fold defaultstate="collapsed" desc="gui element mutators">
    private void setLockChB(JCheckBox chB, boolean state) {
        chB.setEnabled(false);
        chB.setSelected(state);
    }

    private void filterLists(JComboBox coB, Object[] invalidOptions) {
        hjhhj
        ComboBoxModel cbm = coB.getModel();
        ArrayList<String> ar = new ArrayList();
        cardGradeCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Card Grade", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        System.out.println(cbm.toString());
    }
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToOrderBTN;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JTextField boxDepthTB;
    private javax.swing.JTextField boxHeightTB;
    private javax.swing.JList boxList;
    private javax.swing.JTextField boxWidthTB;
    private javax.swing.JComboBox cardGradeCoB;
    private javax.swing.JLabel costLbl;
    private javax.swing.JPanel dimensionPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox numColorsCoB;
    private javax.swing.JSpinner qtySpn;
    private javax.swing.JCheckBox reinforcedBottomChB;
    private javax.swing.JCheckBox reinforcedCornersChB;
    private javax.swing.JButton resetBtn;
    private javax.swing.JCheckBox sealableTopChB;
    // End of variables declaration//GEN-END:variables
}
